### ISSUE TITLE
News about Frametrail

### ISSUE THREAD

**Issue by lucasa** [OpenHypervideo/FieldTrip#1]
Hi!
Are you going to release a new version of frametrail with the new code from FieldTrip?

**Comment by lucasa** [comment]
Can I use the new code with the Frametrail UI?

**Comment by OpenHypervideo** [comment]
Sorry for the late reply. The develop branch of the FrameTrail repository already includes the parts which are used in Field Trip: https://github.com/OpenHypervideo/FrameTrail/archive/develop.zip.
However, much of the Field Trip UI (including the overview map and the transitions between episodes) are customized and not part of FrameTrail. FrameTrail is in that sense just the base layer of Field Trip. And yes, if you have a running FrameTrail installation, you can just add the /_data directory from Field Trip into this installation and you'll be able to edit all the episodes via the FrameTrail UI.
